language: scala
scala:
  - 2.10.3
  - 2.11.6
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
script: 
  - travis_retry "./travis.sh"
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success: "./travis_after.sh"
env:
  matrix:
    - TEST_TYPE="framework"
    - TEST_TYPE="blank-app"
  global:
    secure: Sc+Fw9a/cZUbqyGhQrEujg8G2gBlYVVpf7gXcBdFbot5xiHmgvzWXWDxJrkEOVYSvYPWwOnjS2w/fVFF05cCnoT2VVuMxZ3bp/wB1WMEvZ9TLIR2sFUdySohD/VZTV+DiIRZWTZmrlWXXyQmqk/H84n5QBikZZxRmyEHK4WeCag=

